---

- name: Configure and Deploy the hugo blog server
  hosts: webserver
  become: yes

  vars: 
    # override the role's defaults here for this specific deployment
    domain_name: wuweb.westeurope.cloudapp.azure.com
    certbot_email: democritushygge@gmail.com

  roles: 
    - hugo_deploy
